### ISSUE TITLE
Error in piglatinizer_rspec.rb

### ISSUE THREAD

**Issue by daniellecroxton** [learn-co-students/sinatra-mvc-lab-v-000#533]
Lines 18 & 19 of piglatinzer_rspec.rb currently read:
```
    expect(words.piglatinize("spray")).to eq("ayspray")
    expect(words.piglatinize("prays")).to eq("ayspray")
```

They should read:
```
    expect(words.piglatinize("spray")).to eq("rayspay")
    expect(words.piglatinize("prays")).to eq("ayspray")
```

**Comment by johanesteves** [comment]
@daniellecroxton I think ayspray is the correct pig latin for both. I believe its supposed to look for the first vowel and move all constants before that to the end. 

CHeck out these sites and well as wikipedia:

http://www.wordplays.com/pig-latin
http://www.piglatin.org/pig_latin_rules

"For words that begin with consonant sounds, all letters before the initial vowel are placed at the end of the word sequence"

Source: Wiki: https://en.wikipedia.org/wiki/Pig_Latin

**Comment by daniellecroxton** [comment]
Fair enough. I was looking at this site:
http://web.ics.purdue.edu/~morelanj/RAO/prepare2.html
which did not address words that begin with more than two consonants.

I can see from these other sites that you are correct.
